-- DROP DATABASE IF EXISTS gamesdata;

CREATE DATABASE gamesdata
    WITH
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1;

-- These are used to create the tables.
DROP TABLE IF EXISTS players, games;

CREATE TABLE players
(
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 CACHE 1 ),
    name character varying(50) NOT NULL,
    CONSTRAINT PK_players PRIMARY KEY (id),
    CONSTRAINT UQ_players_name UNIQUE (name)
);

CREATE TABLE games
(
    id character varying(30) NOT NULL,
    date TIMESTAMP NOT NULL,
    first_name character varying(30) NOT NULL,
    first_played character varying(8) NOT NULL CHECK (first_played IN ('ROCK', 'PAPER', 'SCISSORS')),
    second_name character varying(30) NOT NULL,
    second_played character varying(8) NOT NULL CHECK (second_played IN ('ROCK', 'PAPER', 'SCISSORS')),
    CONSTRAINT PK_games PRIMARY KEY (id)
);